---
services: docker

language: python
python:
  - 3.6
cache: pip

install:
  - pip install molecule docker

before_script:
  - cd ..
  - mv ansible-role-subsonic hadrienpatte.subsonic
  - cd hadrienpatte.subsonic

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
...
