---
- name: Install Subsonic
  include_tasks: install.yml

- name: Generate self signed SSL certificate
  include_role:
    name: hadrienpatte.self_signed_certificate
  vars:
    self_signed_certificate_FQDN: "{{ subsonic_FQDN }}"
    self_signed_certificate_key_path: "{{ subsonic_certificate_path }}"
    self_signed_certificate_path: "{{ subsonic_certificate_path }}"

- name: Configure {{ subsonic_HTTP_server }}
  include_tasks: HTTP_server.yml
...
