---
platforms:
  - name: debian
    image: minimum2scp/systemd-stretch
    privileged: true
    command: /sbin/init
    published_ports:
      - "80"
      - "443"
      - "4040"
verifier:
  name: testinfra
...
